export const mockVideos = [
  {
    id: "1",
    title: "The Haunting Shadows",
    description:
      "A psychological horror thriller that will keep you on the edge of your seat. When a family moves into an old Victorian house, they discover dark secrets lurking in every corner.",
    genre: "horror",
    year: 2023,
    duration: "2h 15m",
    rating: 8.2,
    watchCount: 15420,
    dateAdded: "2024-01-15",
    coverColor: "#8b0000",
  },
  {
    id: "2",
    title: "Cosmic Laughter",
    description:
      "A hilarious space comedy about an unlikely crew of misfits who accidentally save the galaxy while trying to deliver pizza across the universe.",
    genre: "comedy",
    year: 2024,
    duration: "1h 45m",
    rating: 7.8,
    watchCount: 23150,
    dateAdded: "2024-02-20",
    coverColor: "#ffd700",
  },
  {
    id: "3",
    title: "Neural Network",
    description:
      "In a dystopian future where consciousness can be uploaded, a hacker discovers a conspiracy that threatens the very nature of human existence.",
    genre: "sci-fi",
    year: 2023,
    duration: "2h 30m",
    rating: 9.1,
    watchCount: 45230,
    dateAdded: "2024-01-08",
    coverColor: "#0066ff",
  },
  {
    id: "4",
    title: "Thunder Strike",
    description:
      "An explosive action thriller featuring high-octane chase sequences and spectacular stunts as an elite agent races against time to prevent global catastrophe.",
    genre: "action",
    year: 2024,
    duration: "2h 05m",
    rating: 8.5,
    watchCount: 38750,
    dateAdded: "2024-03-10",
    coverColor: "#ff4500",
  },
  {
    id: "5",
    title: "Midnight Terrors",
    description:
      "A collection of spine-chilling tales that explore the darkest corners of human fear. Each story more terrifying than the last.",
    genre: "horror",
    year: 2023,
    duration: "1h 55m",
    rating: 7.9,
    watchCount: 19840,
    dateAdded: "2024-01-25",
    coverColor: "#660000",
  },
  {
    id: "6",
    title: "The Last Laugh",
    description:
      "A heartwarming comedy-drama about a retired comedian who returns to the stage one last time to reconnect with his estranged family.",
    genre: "comedy",
    year: 2024,
    duration: "1h 38m",
    rating: 8.0,
    watchCount: 12650,
    dateAdded: "2024-02-14",
    coverColor: "#ff69b4",
  },
  {
    id: "7",
    title: "Quantum Paradox",
    description:
      "Scientists discover a way to manipulate time itself, but their experiments unleash consequences that threaten to unravel reality.",
    genre: "sci-fi",
    year: 2023,
    duration: "2h 20m",
    rating: 8.7,
    watchCount: 31200,
    dateAdded: "2024-01-30",
    coverColor: "#00ffff",
  },
  {
    id: "8",
    title: "Broken Dreams",
    description:
      "A powerful drama following three generations of a family as they navigate love, loss, and the pursuit of the American Dream.",
    genre: "drama",
    year: 2024,
    duration: "2h 45m",
    rating: 9.3,
    watchCount: 28900,
    dateAdded: "2024-03-05",
    coverColor: "#9370db",
  },
  {
    id: "9",
    title: "Velocity",
    description:
      "A high-speed action adventure where a street racer gets caught up in an international conspiracy involving stolen government technology.",
    genre: "action",
    year: 2024,
    duration: "1h 50m",
    rating: 7.6,
    watchCount: 42100,
    dateAdded: "2024-02-28",
    coverColor: "#ff8c00",
  },
  {
    id: "10",
    title: "The Crimson Manor",
    description:
      "A gothic horror masterpiece set in a remote mansion where guests begin disappearing one by one during a weekend retreat.",
    genre: "horror",
    year: 2023,
    duration: "2h 10m",
    rating: 8.4,
    watchCount: 22750,
    dateAdded: "2024-01-12",
    coverColor: "#800020",
  },
  {
    id: "11",
    title: "Galactic Odyssey",
    description:
      "An epic space opera spanning multiple worlds as a rebel alliance fights against an oppressive galactic empire.",
    genre: "sci-fi",
    year: 2024,
    duration: "2h 55m",
    rating: 9.0,
    watchCount: 67800,
    dateAdded: "2024-03-15",
    coverColor: "#4169e1",
  },
  {
    id: "12",
    title: "Silent Echoes",
    description:
      "An intimate drama exploring the complex relationships within a small town when long-buried secrets come to light.",
    genre: "drama",
    year: 2023,
    duration: "2h 25m",
    rating: 8.8,
    watchCount: 18500,
    dateAdded: "2024-02-05",
    coverColor: "#663399",
  },
]
